<? $list = $this->params->getSortList(); if (!empty($list)): ?>

  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <!-- <label for="sort_options_1"><?=$this->transEsc('Sort')?></label> -->
    <? if (count($list) == 2): ?>
      <!-- if there are two entries, a toggle will do -->
      <? foreach ($list as $sortType => $sortData): ?>
        <? if ($sortData['selected']): ?>
          <!-- for future use - maybe output this before or near the switch button... -->
          <? $cur_sort = 'Sorted by: '.$this->transEsc($sortData['desc']) ?>
        <? else: ?>
          <!-- ... but the button has to be put in a variable too -->
          <button type="submit" name="sort" value="<?=$this->escapeHtmlAttr($sortType)?>" <?=$sortData['selected']?' style="display: none"':'class="btn btn-primary"'?>><i class="fa fa-sort-numeric-desc"></i> 
            <?=$this->transEsc('Sort')?>
            <?=$this->transEsc($sortData['desc'])?></button>
        <? endif; ?>
      <? endforeach; ?>
      <!-- Output $cur_sort and button here -->
    <? else: ?>
      <!-- Otherwise do it the old way and add a select box -->
      <select id="sort_options_1" name="sort" class="jumpMenu form-control">
        <? foreach ($list as $sortType => $sortData): ?>
          <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
        <? endforeach; ?>
      </select>
      <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
    <? endif; ?>
  </form>
<? endif; ?>
