<?
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<div class="tub-doi">
  <? $doi = $this->driver->getContainerDoi(); ?>
    <? if (!empty($doi)): ?>
      <span class="doi_outer"><span class="doi_prefix">DOI</span><span class="doi_link"><a href="https://doi.org/<?=$doi?>"><?=$doi?></a></span></span>
    <? endif; ?>
</div>


<? if (!empty($urls) || $openUrlActive): ?>
  <h3 class="urllabel"><?=$this->transEsc("Internet")?></h3>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
  <? if (!empty($urls)): ?>
    <span class="marclinks">
    <? foreach ($urls as $current): ?>
      <br/><span class="externalurl"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" rel="tooltip"><i class="fa fa-download"></i> <?=$this->escapeHtml($current['desc'])?></a></span>
    <? endforeach; ?>
    </span>
  <? endif; ?>
<? endif; ?>
