<?
    // Set page title.
    $this->headTitle($this->translate('Tomes/Volumes') . ': ' . $this->driver->getBreadcrumb());

    $vols = $this->tab->getMultipartList();
?>

In dieser Bandliste sind <span id="volcount"></span> Titel enthalten.
<table class="datagrid extended">
    <colgroup>
      <col style="width: 10%;">
      <col style="width: 60%;">
      <col style="width: 30%;">
    </colgroup>
    <thead>
      <tr>
        <th>Band</th>
        <th>Titel</th>
        <th>Jahr</th>
      </tr>
    </thead>
    <tbody class="multipartlist">
  <? $i = 0; ?>
  <? foreach ($vols as $data): ?>
    <tr
    <? if ($i > 5): ?>
    class="offscreen"
    <? endif ?>
    >
    <td><a href=""><?=$data['partNum']?></a></td>
    <td>
    <a href="">
    <?=$this->escapeHtml($data['title'])?>
    </a>
    </td>
    <td><a href=""><?=$data['date']?></a></td>
    </tr>
    <? $i++; ?>
  <? endforeach; ?>
    </tbody>
</table>
<ul class="pager">
    <li class="next-parts"> Show more </li>
    <li class="setback-parts" style="display: none;"> Reset </li>
    <li class="all-parts"> Show all </li>
</ul>
<script src="/vufind2/themes/bootstrap3-tub/js/multipart.js" type="text/javascript"></script>
