<?
    // Set page title.
    $this->headTitle($this->translate('Tomes/Volumes') . ': ' . $this->driver->getBreadcrumb());

    // Grab review data:
    $vols = $this->tab->getContent();

?>
<? if ($vols['volscount'] > 0): ?>
  <? if ($vols['volscount'] > 200): ?>
    In dieser Bandliste sind <?=$vols['volscount']?> Titel enthalten. Es werden nicht alle angezeigt.
  <? endif; ?>
  <table class="datagrid extended">
    <colgroup>
      <col style="width: 10%;">
      <col style="width: 60%;">
      <col style="width: 30%;">
    </colgroup>
    <thead>
      <tr>
        <th>Band</th>
        <th>Titel</th>
        <th>Jahr</th>
      </tr>
    </thead>
    <tbody>
  <? foreach ($vols['vols'] as $data): ?>
    <tr>
    <td><a href="<?=$this->recordLink()->getUrl($data)?>"><?=$data->getVolumeInformation($this->driver->getUniqueId())?></a></td>
    <td>
    <?
        $t = $data->getTitle();
        $s = $t;
        if (is_array($t) === true) {
            $s = $t[0];
        }
    ?>
    <a href="<?=$this->recordLink()->getUrl($data)?>">
    <?=$this->escapeHtml($s)?>
    <?
        $ed = $data->getEditionsFromMarc();
        if (count($ed) > 0) {
            echo $ed[0];
        }
    ?>
    </a>
    </td>
    <td><a href="<?=$this->recordLink()->getUrl($data)?>"><?=$data->getPublicationDates()[0]?></a></td>
    </tr>
  <? endforeach; ?>
  </tbody>
  </table>
<? else: ?>
  <?=$this->transEsc('No volumes were found for this record')?>.
<? endif; ?>
