<?
  $searchTabs = $this->searchtabs()->getTabConfig($this->params->getsearchClassId(), $this->params->getDisplayQuery(), $this->params->getSearchHandler(), $this->params->getSearchType());
var_dump($searchTabs);
?>
<? if (count($searchTabs) > 0): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('nohit_change_tab', array('%%activeTab%%' => $this->transEsc($this->recommend->getActiveTab($searchTabs))))?>
    <ul>
    <? foreach ($searchTabs as $tab): ?>
        <? if ($tab['selected'] === false): ?>
        <li>
            <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>">
                <?=$this->transEsc($tab['label']); ?>
            </a>
        </li>
        <? endif; ?>
    <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>
