<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

      // Deal with cart stuff:
      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'loading' => 'Loading',
            'sms_success' => 'sms_success',
            'number_thousands_separator' => ['number_thousands_separator', null, ',']
          )
        );
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
              'no_tags' => 'No Tags'
            )
          );
        }
        // TZ:  Maybe add an additional custom language ini like de_tub (https://vufind.org/wiki/vufind2:language_localization_support)
        //         And: could put these strings somewhere "closer". Best would be in checks_item_statused.js itself. 
        //              Or maybe in AjaxController via loading a special template (like for the status messages).
        $this->jsTranslations()->addStrings(
          array(
            'notforloan' => $this->transEsc('status_notforloan'),
            'missing' => $this->transEsc('status_missing'),
            'lost' => $this->transEsc('status_lost'),
            'hold_place' => $this->transEsc('hold_place'),
            'recall_this' => $this->transEsc('Recall this'),

            'loc_modal_Title_shelf_generic' => $this->translate('loc_modal_Title_shelf_generic'),
            'loc_modal_Title_refonly_generic' => $this->translate('loc_modal_Title_refonly_generic'),

            'loc_btn_Hover_shelf_lbs' => $this->transEsc('loc_btn_Hover_shelf_lbs'),
            'loc_modal_Title_shelf_lbs' => $this->translate('loc_modal_Title_shelf_lbs'),
            'loc_modal_Body_shelf_lbs' => $this->translate('loc_modal_Body_shelf_lbs'),
            'loc_modal_Foot_shelf_lbs' => $this->translate('loc_modal_Foot_shelf_lbs'),

            'loc_btn_Hover_shelf_ls1' => $this->transEsc('loc_btn_Hover_shelf_ls1'),
            'loc_modal_Title_shelf_ls1' => $this->translate('loc_modal_Title_shelf_ls1'),
            'loc_modal_Body_shelf_ls1' => $this->translate('loc_modal_Body_shelf_ls1'),
            'loc_modal_Foot_shelf_ls1' => $this->translate('loc_modal_Foot_shelf_ls1'),

            'loc_btn_Hover_shelf_ls2' => $this->transEsc('loc_btn_Hover_shelf_ls2'),
            'loc_modal_Title_shelf_ls2' => $this->translate('loc_modal_Title_shelf_ls2'),
            'loc_modal_Body_shelf_ls2' => $this->translate('loc_modal_Body_shelf_ls2'),
            'loc_modal_Foot_shelf_ls2' => $this->translate('loc_modal_Foot_shelf_ls2'),

            'loc_btn_Hover_sem' => $this->transEsc('loc_btn_Hover_sem'),
            'loc_modal_Title_sem' => $this->translate('loc_modal_Title_sem'),
            'loc_modal_Body_sem' => $this->translate('loc_modal_Body_sem'),
            'loc_modal_Foot_sem' => $this->translate('loc_modal_Foot_sem'),

            'loc_btn_Hover_eonly' => $this->translate('loc_btn_Hover_eonly'),
            'loc_modal_Title_eonly' => $this->translate('loc_modal_Title_eonly'),
            'loc_modal_Body_eonly' => $this->translate('loc_modal_Body_eonly'),
            'loc_modal_Foot_eonly' => $this->translate('loc_modal_Foot_eonly'),

            'loc_btn_Hover_order' => $this->transEsc('loc_btn_Hover_order'),
            'loc_modal_Title_order' => $this->translate('loc_modal_Title_order'),
            'loc_modal_Body_order' => $this->translate('loc_modal_Body_order'),
            'loc_modal_Foot_order' => $this->translate('loc_modal_Foot_order'),

            'loc_btn_Hover_reserve' => $this->transEsc('loc_btn_Hover_reserve'),
            'loc_modal_Title_reserve' => $this->translate('loc_modal_Title_reserve'),
            'loc_modal_Body_reserve' => $this->translate('loc_modal_Body_reserve'),
            'loc_modal_Foot_reserve' => $this->translate('loc_modal_Foot_reserve'),

            'loc_btn_Hover_multi' => $this->transEsc('loc_btn_Hover_multi'),
            'loc_modal_Title_multi' => $this->translate('loc_modal_Title_multi'),
            'loc_modal_Body_multi' => $this->translate('loc_modal_Body_multi'),
            'loc_modal_Foot_multi' => $this->translate('loc_modal_Foot_multi'),

            'loc_btn_Hover_service_da' => $this->transEsc('loc_btn_Hover_service_da'),
            'loc_modal_Title_service_da' => $this->translate('loc_modal_Title_service_da'),
            'loc_modal_Body_service_da' => $this->translate('loc_modal_Body_service_da'),
            'loc_modal_Foot_service_da' => $this->translate('loc_modal_Foot_service_da'),

            'loc_btn_Hover_service_else' => $this->transEsc('loc_btn_Hover_service_da'),
            'loc_modal_Title_service_else' => $this->translate('loc_modal_Title_service_da'),
            'loc_modal_Body_service_else' => $this->translate('loc_modal_Body_service_da'),
            'loc_modal_Foot_service_else' => $this->translate('loc_modal_Foot_service_da')
          )
        );
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }
    ?>
    <?=$this->headScript()?>

    <?
    // Get Wordpress-Theme head
    echo file_get_contents('https://www.tub.tuhh.de/ext/wp-frame/index.php?blog_element=head&mylang='.$this->layout()->userLang);
    ?>
  </head>
<!--
  body
  Use Wordpress-Theme body instead; add missing "content" div (style="background-color: transparent" ...) -->
<!--    span id="wp-head" role="banner" class="hidden-print">-->
      <? echo file_get_contents('https://www.tub.tuhh.de/ext/wp-frame/index.php?blog_element=body&mylang='.$this->layout()->userLang); ?>
<!--    /span>-->
  <div id="primary">
<!-- End Wordpress -->

    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    
    <header role="banner" class="hidden-print">
      <div class="container navbar">
        <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
        <?=$this->render('header.phtml')?>
      </div>
      <div class="container">
        <nav class="nav searchbox hidden-lg hidden-print">
          <?=$this->layout()->searchbox ?>
        </nav>
        <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
          && !empty($this->layout()->breadcrumbs)
          && $this->layout()->breadcrumbs !== false
        ): ?>
          <ul class="breadcrumb hidden-print">
          <? if(is_array($this->layout()->breadcrumbs)): ?>
            <? if(count($this->layout()->breadcrumbs) > 1): ?>
              <?=$this->render('breadcrumbs/multi.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title,
                  'end'     => $this->layout()->breadcrumbEnd,
                  'from'    => $this->layout()->from
                )) ?>
            <? else: ?>
              <?=$this->render('breadcrumbs/default.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title
                )) ?>
            <? endif; ?>
          <? else: ?>
            <?=$this->layout()->breadcrumbs ?>
          <? endif; ?>
          </ul>
        <? endif; ?>
      </div>
    </header>
    <div role="main" class="main template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="container">
        <?=$this->layout()->content ?>
      </div>
    </div>
    <footer role="contentinfo" class="hidden-print">
      <div class="container">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>

    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div class="modal-body"><i class="tub_loading fa fa-circle-o-notch fa-spin"></i> <?=$this->transEsc('Loading')?>...</div>
        </div>
      </div>
    </div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
  <!-- START close Wordpress (?) -->
    </div>
    <? echo '</div></div>' ?>
  <!-- END close Wordpress (?) -->
  </body>
</html>
