<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <ul class="recordTabs nav nav-tabs">
        <? foreach ($this->tabs as $tab => $obj): ?>
        <? // add current tab to breadcrumbs if applicable:
          $desc = $obj->getDescription();
          if ($desc == 'Staff View') {
              $desc = '<span style="color:#FFFFFF">' . $this->translate($desc) . '</span>';
          } else {
              $desc = $this->translate($desc);
          }
          $tab_classes = array();
          if (0 === strcasecmp($this->activeTab, $tab)) {
            $tab_classes[] = 'active';
            $this->layout()->breadcrumbs .= '<li class="active">' . $desc . '</li>';
            $activeTabObj = $obj;
          }
          if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
          if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
        ?>
        <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
          <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$desc?></a>
        </li>
        <? endforeach; ?>
      </ul>
    <? endif; ?>

    <div class="tab-content" id="record-tabs">
      <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    </div>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>
  </div>
</div>
