<?
  $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType);
?>
<? if (count($searchTabs) > 0): ?>
    <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
        <li<?=$tab['label']=="tab_articles" ? ' rel="tooltip" title="'.$this->transEsc('tab_articles_title').'" class="searchTab articles' : ' rel="tooltip"  title="'.$this->transEsc('tab_books_title').'" class="searchTab books'?> <?=$tab['selected'] ? ' active"' : '"'?>>
            <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>">
                <?=$this->transEsc($tab['label']); ?>
                <span id="<?=$tab['label']=="tab_articles" ? 'hitsprimo' : 'hitsgbv'?>" class="matches <?=$tab['selected'] ? 'active"' : '"'?>><?=$tab['selected'] ? '('.$this->localizedNumber($this->results->getResultTotal()).')' : ''?></span>
            </a>
        </li>
    <? endforeach; ?>
    </ul>
<? endif; ?>
