<?
    $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType);
    $i = 0;
 ?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
  <? foreach ($searchTabs as $tab): ?>
    <? $i++ ?>
    <li<?=$tab['label']=="tab_articles" ? ' title="'.$this->transEsc('tab_articles_title').'" class="searchTab articles' : ' title="'.$this->transEsc('tab_books_title').'" class="searchTab books'?>
      <?=$tab['selected'] ? ' mainactive active"' : '"'?>>
      <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>">
      
      <?=$this->transEsc($tab['label']); ?>
      <span id="<?=$tab['label']=="tab_articles" ? 'hitsprimo' : 'hitsgbv'?>" class="matches <?=$tab['selected'] ? 'mainactive active"' : '"'?>><?=$tab['selected'] ? '('.$this->localizedNumber($this->results->getResultTotal()).')' : ''?></span>
      </a>
    </li>
  <? endforeach; ?>
  </ul>
<? endif; ?>
