<? $similarRecords = $this->related->getResults(); ?>
<? if ($similarRecords->getTotal() > 0): ?>
<h4><?=$this->transEsc('Similar Items')?></h4>
  <ul class="nav nav-list">
    <? foreach ($similarRecords as $data): ?>
      <li style="padding-top: 10px; font-size:smaller;">
      <i class="tub_lielement fa fa-angle-right" style="margin-left:-21px;"></i>
        <? $formats = $data->getFormats(); if (count($formats) > 0): ?>
          <span class="<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>">
        <? else: ?>
          <span>
        <? endif; ?>
        <a href="<?=$this->recordLink()->getUrl($data)?>">
        <?
            $t = $data->getTitle();
            $s = $t;
            if (is_array($t) === true) {
                $s = $t[0];
            }
        ?>
        <?=$this->escapeHtml($s)?>
        </a>
        </span>
        <? $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
          <br/><?=$this->transEsc('By')?>: <?=$this->escapeHtml($author);?>
        <? endif; ?>
        <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          (<?=$this->escapeHtml($pubDates[0])?>)
        <? endif; ?>
      </li>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <!--<p><?=$this->transEsc('Cannot find similar records')?></p>-->
<? endif; ?>