<div class="row">
  <div class="col-xs-4">
    <p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
    </ul>
    <br/><a href="<?=$this->url('search-advanced')?>" style="color:white;">E</a>
  </div>
<!--
  <div class="col-sm-3">
    <p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
    </ul>
  </div>
-->
  <div class="col-xs-4">
    <p><strong><?=$this->transEsc('Services')?></strong></p>
    <ul>
      <li><?=$this->translate('wp_link_getalibrarycard')?></li>
      <? if ($_REQUEST['lookfor'] != ''): ?>
          <li><a href="https://katalog.b.tuhh.de/DB=1/<?=$this->layout()->userLang?>/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=<?=$_REQUEST['lookfor']?>" target="_blank"><?=$this->transEsc('classic_catalog')?></a></li>
      <? else: ?>
          <li><a href="https://katalog.b.tuhh.de/DB=1/<?=$this->layout()->userLang?>/" target="_blank"><?=$this->transEsc('classic_catalog')?></a></li>
      <? endif; ?>
      <li><?=$this->translate('acq_prop')?></li>
    </ul>
  </div>
  <div class="col-xs-4">
    <p><strong><?=$this->transEsc('Information')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
      <li><?=$this->translate('wp_link_tubfindblog')?></li>
    </ul>
  </div>
</div>

<?
echo file_get_contents('https://www.tub.tuhh.de/ext/wp-frame/index.php?blog_element=footer&mylang='.$this->layout()->userLang);
?>

<div class="row powered-by">
    <?=$this->layout()->poweredBy ?>
</div>
