<?
  // Set up additional search box, which is not getting displayed:
  $this->layout()->searchboxN = $this->context($this)->renderInContext(
      'search/searchbox.phtml',
      array(
        'lookfor' => $lookfor
      )
  );
?>
<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button>
  <a role="logo" class="navbar-brand-beta" href="<?=$this->url('home')?>"> </a>
</div>
<? /* 2015-12-27: What's the point of always loading a search form for >1200px and never showing it?
  if ($this->layout()->searchbox !== false): ? >
  <section class="visible-lg">
    <?=$this->layout()->searchbox ? >
  </section>
< ? endif; */ ?>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <nav>
    <ul class="nav navbar-nav navbar-right flip">
    <li>
      <a href="#" id="info-help" rel="tooltip" title="<?=$this->translate('help_menu_Hover_clueless')?>" class="locationInfox modal-link hidden-print"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->translate('help_menu_Link_clueless')?>
      <span data-title="<?=$this->translate('help_modal_Title_clueless')?>" data-location="TEST" class="modal-dialog hidden"><?=$this->transEsc('help_modal_Body_clueless')?></span></a>
    </li>
      <? if ($this->feedback()->tabEnabled()): ?>
        <li>
          <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
        </li>
      <? endif; ?>
      <? $cart = $this->cart(); if ($cart->isActive()): ?>
        <li id="cartSummary">
          <a id="cartItems" class="modal-link" rel="tooltip" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="tub_lielement fa fa-angle-right"></i> <span class="cartItemsCount"><?=count($cart->getItems())?></span> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
        </li>
      <? endif; ?>
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" rel="tooltip" title="<?=$this->transEsc("Favorites")?>"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->transEsc("Favorites")?></a>
        </li>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" rel="tooltip" title="<?=$this->transEsc("Log Out")?>"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->transEsc("Log Out")?></a>
        </li>
        <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
          <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
          <? else: ?>
            <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" rel="tooltip" title="<?=$this->transEsc("Login")?>"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->transEsc("Favorites")?></a>
          <? endif; ?>
        </li>
      <? endif; ?>

      <li>
        <a href="<?=$this->transEsc('mylibrary-login-url')?>" target="_blank" class="modal-link" rel="tooltip" title="<?=$this->transEsc("My Library")?>"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->transEsc("My Library")?></a>
      </li>

      <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
        <li class="dropdown">
          <form method="post" name="themeForm" action="" id="themeForm">
            <input type="hidden" name="ui"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <? foreach ($this->layout()->themeOptions as $current): ?>
              <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
            <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="tub_lielement fa fa-angle-right"></i> <?=$this->transEsc("Password")?></a>
          <ul class="dropdown-menu">
            <!-- TZ 2015-09-26: old way
              <li><a href="https://www.tub.tu-harburg.de/ext/lbspw" target="_blank"><?=$this->transEsc('Change Password')?></a></li>
              <li><a href="https://www.tub.tu-harburg.de/ext/lbspw/forgotten" target="_blank"><?=$this->transEsc('Lost Password?')?></a></li>
            -->
            <li><a href="#" id="info-pwchange" class="locationInfox modal-link"><?=$this->transEsc('Change Password')?><span data-title="<?=$this->transEsc('Change Password')?>" data-location="Undefined" data-iframe="https://www.tub.tu-harburg.de/ext/lbspw" class="modal-dialog hidden"><?=$this->transEsc('Blablub und so weiter')?></span></a></li>
            <li><a href="#" id="info-pwrequest" class="locationInfox modal-link"><?=$this->transEsc('Lost Password?')?><span data-title="<?=$this->transEsc('Lost Password?')?>" data-location="Undefined" data-iframe="https://www.tub.tu-harburg.de/ext/lbspw/forgotten" class="modal-dialog hidden"><?=$this->transEsc('Blablub und so weiter')?></span></a></li>
          </ul>
      </li>

      <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <li class="dropdown" id="dropdown_language">
          <form method="post" name="langForm" action="" id="langForm">
            <input type="hidden" name="mylang"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" id="href_<?=$langCode?>" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
          <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>
    </ul>
    </nav>
  </div>
<? endif; ?>
